### ISSUE TITLE
Don't use `git add .`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/git-basics#10]
Explain to developers why it's bad practice and tell the never to use this command.  Repeat as necessary.

If/when that sinks in, tell them about the one exception (template/generator initial commit).

**Comment by jrhorn424** [comment]
Related to #4

**Comment by jrhorn424** [comment]
Closed as of 5c75e031acf0b99eb606437364eacc5327365da9

**Comment by jrhorn424** [comment]
@gaand Did we miss anything?

**Comment by gaand** [comment]
I would have said "add files explicitly". So multiple but complete path for each.

**Comment by jrhorn424** [comment]
Addressed by ee81d95b541f0ac5131b621ddbc4ceda82cf9c90

**Comment by gaand** [comment]
Looks good to me.
