### ISSUE TITLE
Explain why one should not use `git commit -m "<one line message>"`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/git-basics#11]
Explain ramifications from an employment perspective. 

Model good commit messages, headline, blank line, detail.

Not even on first commit:

``` txt
Initial commit

Starting from `ga-wdi-boston/js-template`.
```

**Comment by jrhorn424** [comment]
related to #4

**Comment by jrhorn424** [comment]
This appears to be fixed as of 5c75e031acf0b99eb606437364eacc5327365da9. @gaand please confirm.

**Comment by gaand** [comment]
I don't see it in the diff. Is there a different commit?

**Comment by jrhorn424** [comment]
Several. "as of" was meant to imply the commits weren't cohesive enough. Apologies for that. Let me find a diff.

**Comment by gaand** [comment]
Ah. Sorry. I'm doing this from my iPhone.

**Comment by jrhorn424** [comment]
@gaand https://github.com/ga-wdi-boston/git-basics/compare/1a3f9ff3d47c8c682bc1421f113939d4539772fc...5c75e031acf0b99eb606437364eacc5327365da9

**Comment by jrhorn424** [comment]
Oops! Sorry, this wasn't actually addressed yet. Wrong issue.

**Comment by jrhorn424** [comment]
The title was addressed, but not the body.

**Comment by RealWeeks** [comment]
@jrhorn424 addressed in commit 23bd767. Thoughts?

**Comment by gaand** [comment]
I think this is done.  I'll close.  please reopen if I missed something outstanding for this issue.
