### ISSUE TITLE
Show developers `git rm` to stage a delete of file

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/git-basics#14]

**Comment by gaand** [comment]
Maybe mention that the history of the file remains?

**Comment by RealWeeks** [comment]
@gaand Your suggesting to tell them the history remains but don't explicitly mention git rm here?

**Comment by jrhorn424** [comment]
I believe I suggested this as a parallel to `git add`. Add and remove single files at a time to stage them. **Also** mention that the history remains, and that permanently removing a (sensitive) file from a branch is complicated.

@payne-chris-r Would you take care of this please?
