### ISSUE TITLE
Change formatting

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/git-basics#15]
The following section isn't code or a direct instruction. I don't think `it should be formatted like this`

Committed means that the data is safely stored in your local database. Modified
 means that you have changed the file but have not committed it to your database
 yet. Staged means that you have marked a modified file in its current version
to go into your next commit snapshot.

**Comment by gaand** [comment]
A definition list might be better
- **Comitted** - file is safely stored...
- **Modified** - file is changed...

et cetera

**Comment by RealWeeks** [comment]
@payne-chris-r fixed in commit 5c5c0c3. Okay to close?

**Comment by payne-chris-r** [comment]
Looks good to me!
