### ISSUE TITLE
Adjust order of git stages

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/git-basics#20]
Should be modified, staged, then commited. via @payne-chris-r

**Comment by RealWeeks** [comment]
@payne-chris-r @berziiii updated in commit 3439135. Okay to close?

**Comment by BenGitsCode** [comment]
@payne-chris-r ☝👌❓

**Comment by payne-chris-r** [comment]
I think I was commenting on the order.
Modify->stage->commit
NOT
Commit->modify->stage
It allows us to begin talking about the flow. It wasn't a huge deal just a small improvement.

**Comment by payne-chris-r** [comment]
Ok. I misread that diff. It's ok to be closed. That sentence above should probably follow the same order, but main issue is resolved.

**Comment by jrhorn424** [comment]
I agree, this appears resolved.
