### ISSUE TITLE
Should `git commit -m` be taught or be framed less negatively?

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/git-basics#33]
See https://github.com/ga-wdi-boston/git/issues/23
@nayana487 
>I was kind of put off by the section that said never user git commit -m. That "This is surely a sign of a poor developer and one that does not respect his or her teammate's time." This is how my instructors taught me to write commit messages and what they and pretty much every other developer I know uses in their work flow. When I delivered the lesson, I told the students that what was written in the lesson plan is the opinion of the instructor who wrote the lesson. I personally don't agree with it and this is why. It's ok and encouraged to have differing opinions as developers, but we should be able to intelligently articulate why we prefer one way over another. I did let Matt know ahead of time that I'd be saying this. That said, I don't think such strongly worded opinions should be written into a lesson plan in this way. I think --generally speaking--it's better to present different options and let students figure out what works for them. At least until the shops they end up at tell them otherwise.

@raq929 
>I agree the wording should be changed. Calling people bad developers just isn't helpful. I think the reasoning here (and @gaand might have more to say) is that at this level, developers aren't yet good at writing commit messages. Forcing them to open an editor and write a two line commit message makes them think more critically about what they're doing and produces commit messages that are more helpful to them and to us. (Personally, I only use -m when I'm making a fixup commit, for similar reasons.)

**Comment by BenGitsCode** [comment]
I see that perspective here, but think I agree with @raq929 that the pedagogical value of discouraging `-m` is important in creating good commit habits.

**Comment by MicFin** [comment]
lm01 deliver included stressing not using `commit -m` and the language seemed fine for delivery.  Recommending to close this issue and not change language.
