### ISSUE TITLE
Demo git branching tutorial first level

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/git-basics#8]
See https://github.com/ga-wdi-boston/git-basics-practice/issues/36

**Comment by RealWeeks** [comment]
@jrhorn424 Can you describe a bit more.  I see that #36 is closed now, has this been addressed already @berziiii?

**Comment by payne-chris-r** [comment]
This looks like it was resolved by @berziiii, @jrhorn424 can you confirm we're good to close this?

**Comment by jrhorn424** [comment]
I see nothing in the README that says "let's do the first level of learn git branching together". All I see is a link in extra resources. Please add @payne-chris-r. Thanks!

**Comment by payne-chris-r** [comment]
For clarification, add this: http://learngitbranching.js.org/

**Comment by payne-chris-r** [comment]
@jrhorn424 this is going to add some time to this lesson. I'm fine with doing it, but I would be surprised if we get through this in 1 unit tomorrow...

**Comment by jrhorn424** [comment]
@payne-chris-r For clarification, I mean one level, one exercise. It's just to get used to the UI. It shouldn't add more than 10 minutes. Besides, last time this lesson went a little long, but git-github went short. Please be sure to add your actuals to both lessons in minute resolution.
