### ISSUE TITLE
Mention `git log` options for visualizing branches?

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/git-basics#9]
e.g.
`git log --graph --all --decorate --oneline`

**Comment by gaand** [comment]
Possibly, but it certainly makes sense to mention `git log --name-status`. Not a visualization, but informative.

**Comment by jrhorn424** [comment]
I like this. Thanks @gaand.

``` sh
git log --name-status --graph --all --decorate --oneline
```

**Comment by jrhorn424** [comment]
This is my personal favorite: `git log --oneline --abbrev-commit --all --graph --decorate --color --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset`

**Comment by gaand** [comment]
Potential info overload for new developers?  :-P.  Which doesn't mean I won't explore it. :-).

**Comment by payne-chris-r** [comment]
@jrhorn424 your personal favorite (mentioned above), doesn't work for me. Do we have a consensus on whether or not we should add mention of git log?

**Comment by jrhorn424** [comment]
Confirmed as closed by #17
